#! /bin/sh

killall sxhkd
killall copyq
killall picom
killall flameshot

sxhkd &
copyq -s main &
picom --config /home/lukas/.config/picom/config-bspwm.conf &
flameshot &
~/.config/polybar/bspwm/launch.sh &
eww open main &
~/.config/dunst/launch.sh &
hsetroot -solid "#1e2030" &
#nitrogen --restore &
xsetroot -cursor_name left_ptr &

bspc monitor DisplayPort-1 -d I II III IV V VI
bspc monitor HDMI-A-0 -d VII VIII IX X

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a gnome-calculator state=floating follow=on
bspc rule -a floatingTerminal state=floating
bspc rule -a pomatez state=floating
bspc rule -a copyq-main state=floating
bspc rule -a Emacs state=tiled

bspc config top_padding 0
bspc config focus_follows_pointer true
# bspc config focused_border_color '#b58900'
bspc config focused_border_color '#e0af68'
bspc config normal_border_color '#1a1b26'
bspc config active_border_color '#1a1b26'
bspc config pointer_motion_interval 7ms

bspc config single_monocle true

alacritty --class floatingTerminal &

emacs --daemon &
