#! /bin/sh

killall sxhkd
killall copyq
killall picom
killall deadd-notification-center
kilall flameshot

sxhkd &
copyq -s main &
picom --config /home/lukas/.config/picom/config-bspwm.conf &
deadd-notification-center &
flameshot &
/home/lukas/.config/polybar/bspwm/launch.sh &
hsetroot -solid "#073642" &

bspc monitor DisplayPort-1 -d I II III IV V VI
bspc monitor HDMI-A-0 -d VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a gnome-calculator state=floating follow=on
bspc rule -a floatingTerminal state=floating
bspc rule -a copyq-main state=floating
bspc rule -a Emacs state=tiled

bspc config top_padding 0
bspc config focus_follows_pointer true
bspc config focused_border_color '#b58900'
bspc config normal_border_color '#002b36'
bspc config active_border_color '#002b36'
bspc config pointer_motion_interval 7ms

bspc config single_monocle true
bspc config pointer_follows_focus true

alacritty --class floatingTerminal &
