#! /bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1
wmname LD3D

killall sxhkd
# killall copyq
killall greenclip
killall picom
killall flameshot
killall crowabar

nitrogen --restore &
sxhkd &
greenclip daemon &
picom --config /home/lukas/.config/picom/config.conf &
flameshot &
# eww open main &
~/.config/dunst/launch.sh &
xsetroot -cursor_name left_ptr &

bspc monitor eDP-1 -d I II III IV V VI
# bspc monitor HDMI-A-0 -d VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a gnome-calculator state=floating follow=on
bspc rule -a floatingTerminal state=floating follow=on
bspc rule -a pomatez state=floating

bspc rule -a "Slack" desktop=VI follow=off
bspc rule -a "firefox" desktop=I follow=off

bspc config top_padding 0
bspc config focus_follows_pointer true
bspc config focused_border_color '#E6C384'
bspc config normal_border_color '#1a1b26'
bspc config active_border_color '#1a1b26'
bspc config pointer_motion_interval 7ms

bspc config single_monocle true

alacritty --class floatingTerminal &

crowbar &
